import { describe, it, expect } from "vitest";
import * as fc from "fast-check";
import {
  createFactory,
  userFactory,
  metricFactory,
  activityFactory,
  notificationFactory,
  errorLogEntryFactory,
  UserSchema,
  MetricSchema,
  ActivitySchema,
  NotificationSchema,
  ErrorLogEntrySchema,
} from "./index";

describe("Factory Utilities", () => {
  describe("createFactory", () => {
    it("should create factory with static defaults", () => {
      const factory = createFactory({ name: "Test", value: 42 });
      const result = factory.build();

      expect(result.name).toBe("Test");
      expect(result.value).toBe(42);
    });

    it("should create factory with function defaults", () => {
      let counter = 0;
      const factory = createFactory(() => ({ id: ++counter }));

      expect(factory.build().id).toBe(1);
      expect(factory.build().id).toBe(2);
    });

    it("should apply overrides", () => {
      const factory = createFactory({ name: "Default", value: 0 });
      const result = factory.build({ name: "Custom" });

      expect(result.name).toBe("Custom");
      expect(result.value).toBe(0);
    });

    it("should build list of items", () => {
      const factory = createFactory({ name: "Test" });
      const results = factory.buildList(5);

      expect(results.length).toBe(5);
      results.forEach((item) => {
        expect(item.name).toBe("Test");
      });
    });

    it("should validate against schema", () => {
      const schema = UserSchema;
      const factory = createFactory(
        () => ({
          id: "550e8400-e29b-41d4-a716-446655440000",
          name: "Test",
          email: "test@example.com",
          role: "user" as const,
          createdAt: Date.now(),
        }),
        schema
      );

      const result = factory.build();
      expect(result.name).toBe("Test");
    });

    it("should throw on schema validation failure", () => {
      const schema = UserSchema;
      const factory = createFactory(
        () => ({
          id: "not-a-uuid", // Invalid
          name: "Test",
          email: "not-an-email", // Invalid
          role: "user" as const,
          createdAt: Date.now(),
        }),
        schema
      );

      expect(() => factory.build()).toThrow();
    });
  });

  /**
   * **Feature: code-optimization, Property 8: Factory Schema Validation**
   * **Validates: Requirements 8.5**
   *
   * For any test data generated by a factory function with an associated schema,
   * the generated data SHALL pass schema validation.
   */
  describe("Property 8: Factory Schema Validation", () => {
    it("userFactory should always produce valid users", () => {
      fc.assert(
        fc.property(fc.integer({ min: 1, max: 100 }), () => {
          const user = userFactory.build();
          const result = UserSchema.safeParse(user);
          expect(result.success).toBe(true);
        }),
        { numRuns: 100 }
      );
    });

    it("metricFactory should always produce valid metrics", () => {
      fc.assert(
        fc.property(fc.integer({ min: 1, max: 100 }), () => {
          const metric = metricFactory.build();
          const result = MetricSchema.safeParse(metric);
          expect(result.success).toBe(true);
        }),
        { numRuns: 100 }
      );
    });

    it("activityFactory should always produce valid activities", () => {
      fc.assert(
        fc.property(fc.integer({ min: 1, max: 100 }), () => {
          const activity = activityFactory.build();
          const result = ActivitySchema.safeParse(activity);
          expect(result.success).toBe(true);
        }),
        { numRuns: 100 }
      );
    });

    it("notificationFactory should always produce valid notifications", () => {
      fc.assert(
        fc.property(fc.integer({ min: 1, max: 100 }), () => {
          const notification = notificationFactory.build();
          const result = NotificationSchema.safeParse(notification);
          expect(result.success).toBe(true);
        }),
        { numRuns: 100 }
      );
    });

    it("errorLogEntryFactory should always produce valid error log entries", () => {
      fc.assert(
        fc.property(fc.integer({ min: 1, max: 100 }), () => {
          const entry = errorLogEntryFactory.build();
          const result = ErrorLogEntrySchema.safeParse(entry);
          expect(result.success).toBe(true);
        }),
        { numRuns: 100 }
      );
    });

    it("buildList should produce all valid items", () => {
      fc.assert(
        fc.property(fc.integer({ min: 1, max: 20 }), (count) => {
          const users = userFactory.buildList(count);

          expect(users.length).toBe(count);
          users.forEach((user) => {
            const result = UserSchema.safeParse(user);
            expect(result.success).toBe(true);
          });
        }),
        { numRuns: 50 }
      );
    });
  });

  describe("Pre-built Factories", () => {
    describe("userFactory", () => {
      it("should create valid user", () => {
        const user = userFactory.build();
        expect(user.id).toBeDefined();
        expect(user.name).toBe("Test User");
        expect(user.email).toBe("test@example.com");
      });

      it("should allow overrides", () => {
        const user = userFactory.build({ name: "Custom User", role: "admin" });
        expect(user.name).toBe("Custom User");
        expect(user.role).toBe("admin");
      });
    });

    describe("metricFactory", () => {
      it("should create valid metric", () => {
        const metric = metricFactory.build();
        expect(metric.id).toBeDefined();
        expect(metric.name).toBe("Test Metric");
        expect(typeof metric.value).toBe("number");
      });
    });

    describe("activityFactory", () => {
      it("should create valid activity", () => {
        const activity = activityFactory.build();
        expect(activity.id).toBeDefined();
        expect(activity.type).toBe("create");
        expect(activity.timestamp).toBeDefined();
      });
    });

    describe("notificationFactory", () => {
      it("should create valid notification", () => {
        const notification = notificationFactory.build();
        expect(notification.id).toBeDefined();
        expect(notification.severity).toBe("info");
        expect(notification.read).toBe(false);
      });
    });

    describe("errorLogEntryFactory", () => {
      it("should create valid error log entry", () => {
        const entry = errorLogEntryFactory.build();
        expect(entry.id).toBeDefined();
        expect(entry.error.name).toBe("Error");
        expect(entry.error.message).toBe("Test error message");
      });
    });
  });
});
